# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dolphin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(452, 140)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.txedit_DolphinPath = QtWidgets.QLineEdit(Dialog)
        self.txedit_DolphinPath.setObjectName("txedit_DolphinPath")
        self.horizontalLayout_6.addWidget(self.txedit_DolphinPath)
        self.btn_SelectDolphinFile = QtWidgets.QToolButton(Dialog)
        self.btn_SelectDolphinFile.setObjectName("btn_SelectDolphinFile")
        self.horizontalLayout_6.addWidget(self.btn_SelectDolphinFile)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.txedit_FSdolPath = QtWidgets.QLineEdit(Dialog)
        self.txedit_FSdolPath.setObjectName("txedit_FSdolPath")
        self.horizontalLayout_7.addWidget(self.txedit_FSdolPath)
        self.btn_SelectFSdolFile = QtWidgets.QToolButton(Dialog)
        self.btn_SelectFSdolFile.setObjectName("btn_SelectFSdolFile")
        self.horizontalLayout_7.addWidget(self.btn_SelectFSdolFile)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkbox_Logger = QtWidgets.QCheckBox(Dialog)
        self.chkbox_Logger.setObjectName("chkbox_Logger")
        self.horizontalLayout.addWidget(self.chkbox_Logger)
        self.chkbox_Debugger = QtWidgets.QCheckBox(Dialog)
        self.chkbox_Debugger.setObjectName("chkbox_Debugger")
        self.horizontalLayout.addWidget(self.chkbox_Debugger)
        self.chkbox_AutoExit = QtWidgets.QCheckBox(Dialog)
        self.chkbox_AutoExit.setObjectName("chkbox_AutoExit")
        self.horizontalLayout.addWidget(self.chkbox_AutoExit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btnbox_Dolphin = QtWidgets.QDialogButtonBox(Dialog)
        self.btnbox_Dolphin.setOrientation(QtCore.Qt.Horizontal)
        self.btnbox_Dolphin.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnbox_Dolphin.setObjectName("btnbox_Dolphin")
        self.verticalLayout.addWidget(self.btnbox_Dolphin)
        self.label_6.setBuddy(self.txedit_DolphinPath)
        self.label_7.setBuddy(self.txedit_FSdolPath)

        self.retranslateUi(Dialog)
        self.btnbox_Dolphin.accepted.connect(Dialog.accept)
        self.btnbox_Dolphin.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txedit_DolphinPath, self.btn_SelectDolphinFile)
        Dialog.setTabOrder(self.btn_SelectDolphinFile, self.txedit_FSdolPath)
        Dialog.setTabOrder(self.txedit_FSdolPath, self.btn_SelectFSdolFile)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Path to Dolphin"))
        self.btn_SelectDolphinFile.setText(_translate("Dialog", "..."))
        self.label_7.setText(_translate("Dialog", "Path to filesystem main.dol"))
        self.btn_SelectFSdolFile.setText(_translate("Dialog", "..."))
        self.chkbox_Logger.setText(_translate("Dialog", "Open Logger"))
        self.chkbox_Debugger.setText(_translate("Dialog", "Open Debugger"))
        self.chkbox_AutoExit.setText(_translate("Dialog", "Auto Exit on stopping emulation"))
