# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mextk_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(452, 140)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.txedit_MexTKPath = QtWidgets.QLineEdit(Dialog)
        self.txedit_MexTKPath.setObjectName("txedit_MexTKPath")
        self.horizontalLayout_6.addWidget(self.txedit_MexTKPath)
        self.btn_SelectMexTKFile = QtWidgets.QToolButton(Dialog)
        self.btn_SelectMexTKFile.setObjectName("btn_SelectMexTKFile")
        self.horizontalLayout_6.addWidget(self.btn_SelectMexTKFile)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.btnbox_MexTK = QtWidgets.QDialogButtonBox(Dialog)
        self.btnbox_MexTK.setOrientation(QtCore.Qt.Horizontal)
        self.btnbox_MexTK.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btnbox_MexTK.setObjectName("btnbox_MexTK")
        self.verticalLayout.addWidget(self.btnbox_MexTK)
        self.label_6.setBuddy(self.txedit_MexTKPath)

        self.retranslateUi(Dialog)
        self.btnbox_MexTK.accepted.connect(Dialog.accept)
        self.btnbox_MexTK.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txedit_MexTKPath, self.btn_SelectMexTKFile)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Path to MexTK"))
        self.btn_SelectMexTKFile.setText(_translate("Dialog", "..."))
